version: '3.7'

services:
  redis:
    image: "redis:alpine"
    hostname: redis

  flask:
    build: .
    ports:
      - 5000:5000
    env_file:
      - ~/.env
    depends_on:
      - redis


  celery:
    build: .
    command: celery -A tasks.celery_app worker -l Info
    env_file:
      - ~/.env
    depends_on:
      - redis