version: '3.7'

services:
  redis:
    image: "redis:alpine"
    hostname: redis
    network: redis-net

  flask:
    build: .
    ports:
      - 5000:5000
    env_file:
      - ~/.env
    depends_on:
      - redis
    network: redis-net


  celery:
    build: .
    command: celery -A tasks.celery_app worker -l info
    env_file:
      - ~/.env
    depends_on:
      - redis
    network: redis-net

network:
  - redis-net: